# FROM alpine:3.8
 FROM ubuntu:16.04

 RUN mkdir /dex 
 RUN apt-get update 
 RUN apt-get install -y libssl-dev
 RUN apt-get install -y openssl
 COPY . /dex

 EXPOSE 5555

 WORKDIR /dex

 CMD ["/dex/bin/example-app" ]
